[package]
name = "signify"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

readme = "README.md"
license = "MIT"

homepage = "https://github.com/badboy/signify-rs"
repository = "https://github.com/badboy/signify-rs"

include = [
  "Cargo.toml",
  "README*",
  "LICENSE*",
  "src/**/*",
  "tests/**/*",
  "examples/**/*",
]

[dependencies]
byteorder = "0.5.3"
rust-crypto = "0.2.36"
base64 = "0.2.0"
rand = "0.3.14"
docopt = "0.6"
rustc-serialize = "0.3.19"
